export { default as Apple } from './Apple.svg'
export { default as FaceBook } from './Facebook.svg'
export { default as Google } from './Google.svg'
export { default as Kakaotalk } from './Kakaotalk.svg'
export { default as Naver } from './Naver.svg'
